server:
  port: 8002
  baseUrl: http://localhost:8002

spring:
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: my-secret-password

odm:
  product-plane:
    notification-service:
      address: http://localhost:8006
      active: true
    policy-service:
      active: false
  utility-plane:
    executor-services:
      starter:
        address: http://localhost:9080
        execution-mode: full-control
      cli:
        execution-mode: instrumented